@HelpDesk.API_HostAddress = https://localhost:7153

POST {{HelpDesk.API_HostAddress}}/api/Tickets/8/comments
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
    "comment": "I have restarted the laptop and the issue still occurs.",
    "createdBy": "admin"
}

###

GET {{HelpDesk.API_HostAddress}}/api/users
Authorization: Bearer YOUR_TOKEN_HERE
###

GET {{HelpDesk.API_HostAddress}}/api/Tickets/4

###

PUT {{HelpDesk.API_HostAddress}}/api/Tickets/4
Content-Type: application/json

{
  "title": "Keyboard issue - Updated",
  "description": "The keyboard has been replaced and is working now.",
  "status": "InProgress",
  "priority": "Medium",
  "createdBy": "Michael",
  "assignedTo": "Agent Smith"
}

###

GET {{HelpDesk.API_HostAddress}}/api/Tickets/4

###

DELETE {{HelpDesk.API_HostAddress}}/api/Tickets/8
Authorization: Bearer YOUR_TOKEN_HERE
###

POST {{HelpDesk.API_HostAddress}}/api/Tickets
Content-Type: application/json

{
  "title": "Monitor is not working",
  "description": "The employee's monitor is displaying a black screen.",
  "status": "Open",
  "priority": "Critical",
  "createdBy": "Alex"
}

###

PUT {{HelpDesk.API_HostAddress}}/api/Tickets/8/assign
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
   "assignedTo": "john"
}

###
POST {{HelpDesk.API_HostAddress}}/api/Tickets/4/comments
Content-Type: application/json

{
  "comment": "Testing the comment API response.",
  "createdBy": "Agent Smith"
}

###
GET {{HelpDesk.API_HostAddress}}/api/Tickets/4/comments

###
GET {{HelpDesk.API_HostAddress}}/api/Tickets?status=InProgress

###
GET {{HelpDesk.API_HostAddress}}/api/Tickets?status=Open&priority=High

###
GET {{HelpDesk.API_HostAddress}}/api/Tickets?assignedTo=Agent%20Smith

###
GET {{HelpDesk.API_HostAddress}}/api/Tickets?status=InProgress&assignedTo=Agent%20Smith

###
GET {{HelpDesk.API_HostAddress}}/api/Tickets?page=1&pageSize=2

###

GET {{HelpDesk.API_HostAddress}}/api/Tickets?page=2&pageSize=2

###

POST {{HelpDesk.API_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "username": "john",
  "email": "john@example.com",
  "password": "YOUR_PASSWORD_HERE"
}

###

POST {{HelpDesk.API_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "Password123!"
}

###

PUT {{HelpDesk.API_HostAddress}}/api/Tickets/8/assign
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
  "assignedTo": "john"
}

### Change John to SupportAgent

PUT {{HelpDesk.API_HostAddress}}/api/Users/830ad92a-40aa-486e-8c19-1976ca3ed475/role
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
  "role": "SupportAgent"
}


